# Generated by Django 5.1.5 on 2025-05-07 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementSportif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sport', models.CharField(choices=[('hockey', 'Hockey'), ('football', 'Football'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('basketball', 'Basketball')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('ligue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_depart', models.DateField()),
                ('duree', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('places_disponibles', models.PositiveIntegerField()),
                ('evenements', models.ManyToManyField(to='Agence.evenementsportif')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_personnes', models.PositiveIntegerField()),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.voyage')),
            ],
        ),
    ]
