# Generated by Django 5.1.5 on 2025-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementsportif',
            name='voyage',
            field=models.ManyToManyField(related_name='EvenementSportif', to='Agence.voyage'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='evenements',
            field=models.ManyToManyField(related_name='voyages', to='Agence.evenementsportif'),
        ),
    ]
