# Generated by Django 5.1.5 on 2025-05-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0002_evenementsportif_voyage_alter_voyage_evenements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='evenements',
        ),
        migrations.RemoveField(
            model_name='evenementsportif',
            name='voyage',
        ),
        migrations.AddField(
            model_name='evenementsportif',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='Agence.voyage'),
        ),
    ]
