# Generated by Django 5.1.5 on 2025-05-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0003_remove_voyage_evenements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='evenements',
            field=models.ManyToManyField(related_name='voyages', to='Agence.evenementsportif'),
        ),
        migrations.RemoveField(
            model_name='evenementsportif',
            name='voyage',
        ),
        migrations.AddField(
            model_name='evenementsportif',
            name='voyage',
            field=models.ManyToManyField(related_name='evenements_voyage', to='Agence.voyage'),
        ),
    ]
