# Generated by Django 5.1.5 on 2025-05-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0004_voyage_evenements_remove_evenementsportif_voyage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementsportif',
            name='voyage',
        ),
    ]
