# Generated by Django 5.1.5 on 2025-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0005_remove_evenementsportif_voyage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='evenements',
        ),
        migrations.AddField(
            model_name='evenementsportif',
            name='voyages',
            field=models.ManyToManyField(related_name='evenements', to='Agence.voyage'),
        ),
    ]
