# Generated by Django 5.1.5 on 2025-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0006_remove_voyage_evenements_evenementsportif_voyages'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='evenements',
            field=models.ManyToManyField(related_name='voyages_evenements', to='Agence.evenementsportif'),
        ),
        migrations.AlterField(
            model_name='evenementsportif',
            name='voyages',
            field=models.ManyToManyField(related_name='evenments_voyages', to='Agence.voyage'),
        ),
    ]
